title: Yes please
author: Moment
email: momentprod02@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Yes please

# social links
github_username:  moment02

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
